name: Frontend CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'lab05/frontend/**'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch: {}

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: false

env:
  CONTEXT_PATH: lab05/frontend
  IMAGE_NAME: lab05-frontend
  PORT: 3000
  ARTIFACT_FILE: lab05-frontend.tar.gz
  ARTIFACT_NAME: lab05-frontend-image

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.CONTEXT_PATH }}/Dockerfile

  build:
    name: build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image (load locally)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:ci
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Save image as artifact (gz)
        run: docker save ${{ env.IMAGE_NAME }}:ci | gzip > ${{ env.ARTIFACT_FILE }}
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_FILE }}
          retention-days: 7

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "✅ Test stage passed — pipeline validation complete"